" general
set nocompatible
set showmatch
set number
set cursorline
set wildmode=longest,list
syntax on

set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=2
set autoindent
filetype plugin indent on

set ignorecase
set hlsearch
set incsearch

set ttyfast
set mouse=a
set clipboard=unnamedplus
set noswapfile
set backupdir=~/.cache/vim
set runtimepath+=~/.local/share/vim

" plugins
" automated installation of vimplug if not installed
if empty(glob('~/.local/share/vim/autoload/plug.vim'))
    silent !curl -fLo ~/.local/share/vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source ~/.config/vim/vimrc
endif
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source ~/.config/vim/vimrc
\| endif

call plug#begin('~/.config/vim/plugged')
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'airblade/vim-gitgutter'
call plug#end()

set termguicolors
colorscheme catppuccin_mocha

" keybindings
nnoremap <C-\> :NERDTreeToggle<CR>
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" statusline
set laststatus=2
set noshowmode

